kernel:
    resource: ../../src/Kernel.php
    type: annotation
security_controllers:
    resource: ../../src/Controller/security/
    type: annotation
api_controllers:
    resource: ../../src/Controller/api/
    type: annotation
vue_controller:
    resource: ../../src/Controller/vue/HomeController.php
    type: annotation